# Site settings
title: Speciation Genomics at FCUL
email: bnevado@fc.ul.pt 
description: Webpage of the Speciation Genomics Research Group
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Bruno Nevado<br/>
  Assistant Professor of Evolutionary Biology<br/>
  Faculty of Sciences, University of Lisbon<br/>
  Centre For Ecology, Evolution and Environmental Changes

location: >
  Campus Faculdade de Ciências da Universidade de Lisboa<br/>
  Edifício C1, Piso 3, sala 2.3.11A<br/>
  1749-016 Lisboa, Portugal

contact: >
  <a href="mailto:bnevado@fc.ul.pt" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact us via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: team
#  - name: research
#  - name: publications
#  - name: teaching
#  - name: blogs
#  - name: about
#  - name: talks
#  - name: software

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
